const ASYNC = {
    APP_INSTALL: '@APP_INSTALL',
    DAILY_LOGIN: '@DAILY_LOGIN',
    ONBOARDING: '@ONBOARDING_COMPLETED',
    TOKEN: '@TOKEN',
    THEME: '@THEME',
    USER_ACTIVITY: '@USER_ACTIVITY',
    LANGUAGE: '@LANGUAGE',
    FCM_TOKEN: '@FCM_TOKEN',
    APP_VERSION: '@APP_VERSION',
}

export default ASYNC
