import COLORS from "./colors"

const LIGHT_THEME = {
    BAR_STYLE: 'dark-content',
    SYSTEM_BAR_STYLE: 'dark',

    PRIMARY: COLORS.PRIMARY,
    SECONDARY: COLORS.SECONDARY,

    BACKGROUND: COLORS.WHITE,
    TEXT: COLORS.BLACK,

    CARDBG: COLORS.BORDER,
}

const DARK_THEME = {
    BAR_STYLE: 'light-content',
    SYSTEM_BAR_STYLE: 'light',

    PRIMARY: COLORS.PRIMARY,
    SECONDARY: COLORS.SECONDARY,

    BACKGROUND: COLORS.BACKGROUND,
    TEXT: COLORS.WHITE,

    CARDBG: COLORS.SURFACE,
}


export { LIGHT_THEME, DARK_THEME }